"use client";

import { useEffect, useRef, useState } from "react";
import { GameArtwork } from "@/components/artwork";
import { Button, ProgressBar } from "@/components/ui";
import { WORKING_MEMORY_BLOCK_SIZE, WORKING_MEMORY_SESSION_SECONDS, chooseTrialType, classifyTrial, createSequence, createSummary, expectedSequence, nextWorkingMemoryDifficulty, visualStimuli, workingMemoryParams, workingMemorySessionStore, type WorkingMemoryAudience, type WorkingMemoryTrial, type WorkingMemoryTrialType } from "@/features/working-memory";

type Phase = "intro" | "example" | "countdown" | "presenting" | "recall" | "done";
type TrialSeed = { trialType: WorkingMemoryTrialType; stimulusSequence: string[]; expectedSequence: string[]; presentationStartedAt: number; presentationEndedAt: number };
const labels: Record<WorkingMemoryTrialType, string> = { forward: "Aynı sırayla tekrar et", reverse: "Sırayı tersten tekrar et", spatial: "Yanan konumları aynı sırayla seç" };

export function WorkingMemoryGame({ audience }: { audience: WorkingMemoryAudience }) {
  const [phase, setPhase] = useState<Phase>("intro"), [count, setCount] = useState(3), [level, setLevel] = useState(audience === "kids" ? 1 : 3), [seed, setSeed] = useState<TrialSeed | null>(null), [visibleIndex, setVisibleIndex] = useState(0), [response, setResponse] = useState<string[]>([]), [trials, setTrials] = useState<WorkingMemoryTrial[]>([]), [remaining, setRemaining] = useState(WORKING_MEMORY_SESSION_SECONDS);
  const id = useRef(`memory-${Math.random().toString(36).slice(2)}`), all = useRef<WorkingMemoryTrial[]>([]), levelRef = useRef(level), end = useRef(0), recallStarted = useRef<number | null>(null), responseRef = useRef<string[]>([]), settled = useRef(false), saved = useRef(false), timeout = useRef<ReturnType<typeof setTimeout> | null>(null);
  const clear = () => { if (timeout.current) clearTimeout(timeout.current); };
  const finish = () => { clear(); if (!saved.current) { workingMemorySessionStore.saveSessionSummary(createSummary(id.current, audience, all.current, levelRef.current)); saved.current = true; } setPhase("done"); };
  const beginTrial = (nextLevel = levelRef.current) => { if (performance.now() >= end.current) return finish(); const params = workingMemoryParams(audience, nextLevel), trialType = chooseTrialType(audience, nextLevel), stimulusSequence = createSequence(trialType, params.sequenceLength), presentationStartedAt = performance.now(); settled.current = false; setSeed({ trialType, stimulusSequence, expectedSequence: expectedSequence(trialType, stimulusSequence), presentationStartedAt, presentationEndedAt: 0 }); setVisibleIndex(0); responseRef.current = []; setResponse([]); setPhase("presenting"); };
  const showNext = () => { if (!seed) return; const params = workingMemoryParams(audience, levelRef.current); if (visibleIndex + 1 < seed.stimulusSequence.length) { timeout.current = setTimeout(() => setVisibleIndex(index => index + 1), params.presentationMs + params.intervalMs); return; } timeout.current = setTimeout(() => { const presentationEndedAt = performance.now(); setSeed(current => current ? { ...current, presentationEndedAt } : current); recallStarted.current = presentationEndedAt; setPhase("recall"); }, params.presentationMs); };
  const complete = (sequence: string[]) => { if (!seed || phase !== "recall" || settled.current) return; settled.current = true; const responseEndedAt = performance.now(), params = workingMemoryParams(audience, levelRef.current); const base = { trialId: `${id.current}-${all.current.length}`, sessionId: id.current, audience, difficultyLevel: levelRef.current, trialType: seed.trialType, sequenceLength: seed.stimulusSequence.length, stimulusSequence: seed.stimulusSequence, expectedSequence: seed.expectedSequence, presentationStartedAt: seed.presentationStartedAt, presentationEndedAt: seed.presentationEndedAt }; const result = classifyTrial(base, sequence, recallStarted.current, responseEndedAt, params.responseWindowMs); const next = [...all.current, result]; workingMemorySessionStore.saveTrial(result); all.current = next; setTrials(next); const nextLevel = next.length % WORKING_MEMORY_BLOCK_SIZE === 0 ? nextWorkingMemoryDifficulty(levelRef.current, next.slice(-WORKING_MEMORY_BLOCK_SIZE)) : levelRef.current; levelRef.current = nextLevel; setLevel(nextLevel); timeout.current = setTimeout(() => beginTrial(nextLevel), 650); };
  const select = (value: string) => { if (!seed || phase !== "recall") return; const next = [...responseRef.current, value]; responseRef.current = next; setResponse(next); if (next.length === seed.expectedSequence.length) complete(next); };
  useEffect(() => { if (phase !== "countdown") return; if (!count) { end.current = performance.now() + WORKING_MEMORY_SESSION_SECONDS * 1000; beginTrial(); return; } const timer = setTimeout(() => setCount(value => value - 1), 700); return () => clearTimeout(timer); }, [phase, count]);
  useEffect(() => { if (phase !== "presenting") return; showNext(); }, [phase, visibleIndex]);
  useEffect(() => { if (phase !== "recall") return; const windowMs = workingMemoryParams(audience, levelRef.current).responseWindowMs; const timer = setTimeout(() => complete(responseRef.current), windowMs); return () => clearTimeout(timer); }, [phase]);
  useEffect(() => { if (phase !== "presenting" && phase !== "recall") return; const timer = setInterval(() => setRemaining(Math.max(0, Math.ceil((end.current - performance.now()) / 1000))), 250); return () => clearInterval(timer); }, [phase]);
  useEffect(() => () => clear(), []);
  const params = workingMemoryParams(audience, level);
  if (phase === "intro") return <section className="focus-game"><GameArtwork game="working-memory" audience={audience} aspect="hero" priority alt="Akılda Tut oyun dünyası" className="focus-game__hero" /><p className="eyebrow">Akılda Tut</p><h1>Sırayı aklında tut, sonra yeniden kur.</h1><p>Önce örneği dene. Ardından kısa dizileri doğru sırayla hatırlayacaksın.</p><Button variant="secondary" onClick={() => setPhase("example")}>Örneği gör</Button></section>;
  if (phase === "example") return <section className="focus-game"><p className="eyebrow">Örnek görev</p><h1>{labels.forward}</h1><div className="memory-sequence" aria-label="Örnek sıra"><span>●</span><span>▲</span><span>■</span></div><p>Bu sırayı gördükten sonra aynı sırayla seçersin.</p><Button variant="secondary" onClick={() => setPhase("countdown")}>Başla</Button></section>;
  if (phase === "countdown") return <section className="focus-game focus-game--countdown"><p>Hazır ol</p><strong>{count || "Başla!"}</strong></section>;
  if (phase === "done") { const summary = createSummary(id.current, audience, trials, level); return <section className="focus-game"><GameArtwork game="working-memory" audience={audience} aspect="hero" alt="Akılda Tut tamamlandı" className="focus-game__hero" /><p className="eyebrow">Görev tamamlandı</p><h1>Görev performansın</h1><div className="focus-game__summary"><span><b>%{summary.exactAccuracyPercent ?? "—"}</b>Sıra hatırlama</span><span><b>%{summary.averagePositionalAccuracy ?? "—"}</b>Konum doğruluğu</span><span><b>{summary.workingMemoryScore ?? "Yetersiz veri"}</b>Çalışma Belleği</span></div><Button variant="secondary" onClick={() => window.location.reload()}>Yeni tur</Button></section>; }
  const isSpatial = seed?.trialType === "spatial";
  return <section className="focus-game focus-game--playing"><header><span>Akılda Tut</span><b>{Math.ceil(remaining / 60)} dk</b></header><ProgressBar value={(WORKING_MEMORY_SESSION_SECONDS - remaining) / WORKING_MEMORY_SESSION_SECONDS * 100} label="Oturum ilerlemesi" /><p className="memory-rule">{seed ? labels[seed.trialType] : "Sırayı izle"}</p>{phase === "presenting" && seed && <div className={`memory-board ${isSpatial ? "memory-board--spatial" : ""}`} aria-live="polite">{isSpatial ? <div className="memory-grid">{Array.from({ length: 9 }, (_, index) => <span key={index} className={seed.stimulusSequence[visibleIndex] === String(index) ? "is-lit" : ""}>{index + 1}</span>)}</div> : <div className="memory-sequence"><span>{seed.stimulusSequence[visibleIndex]}</span></div>}<p>İzle, henüz seçim yapma.</p></div>}{phase === "recall" && seed && <div className={`memory-board ${isSpatial ? "memory-board--spatial" : ""}`}><p>Seçimlerin: {response.length ? response.join(" → ") : "Henüz yok"}</p>{isSpatial ? <div className="memory-grid">{Array.from({ length: 9 }, (_, index) => <button key={index} onClick={() => select(String(index))} className="memory-tile" style={{ width: params.tileSize, height: params.tileSize }} aria-label={`Konum ${index + 1}`}>{index + 1}</button>)}</div> : <div className="memory-choices">{visualStimuli.map(value => <button key={value} onClick={() => select(value)} className="memory-tile" style={{ width: params.tileSize, height: params.tileSize }} aria-label={`${value} öğesini seç`}>{value}</button>)}</div>}<Button variant="ghost" onClick={() => { const next = responseRef.current.slice(0, -1); responseRef.current = next; setResponse(next); }} disabled={!response.length}>Geri al</Button></div>}<small>Seviye {level} · {trials.length} görev</small></section>;
}
